apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practice-v1
  template:
    metadata:
      labels:
        app: practice-v1
    spec:
      containers:
      - name: practice-app
        image: ramithas/practice:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: storage-volume
          mountPath: /data    # This matches your App.java FILE_PATH
      volumes:
      - name: storage-volume
        hostPath:
          path: /mnt/data     # Creates a folder on your computer to keep the data
---
apiVersion: v1
kind: Service
metadata:
  name: practice-svc-v1
spec:
  type: NodePort
  selector:
    app: practice-v1
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007